const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const must=p=>assert(fs.existsSync(path.join(root,p)),`${p} missing`);
must('api/_event.js');
must('api/_reminder.js');
must('api/cron/reminders.js');
must('api/admin/reminder-test.js');
const event=require('../api/_event');
const reminder=require('../api/_reminder');
assert.strictEqual(event.EVENT.date,'2026-10-16');
assert.strictEqual(event.EVENT.time,'16:00');
assert.strictEqual(event.EVENT.location,'ROMEXPO, București');
assert.strictEqual(reminder.isReminderDay(new Date('2026-10-15T08:00:00Z')),true);
assert.strictEqual(reminder.isReminderDay(new Date('2026-10-14T08:00:00Z')),false);
const html=reminder.renderReminderEmail({firstName:'Ionuț',participationCode:'SNOO-0001'});
assert(html.includes('Ne vedem mâine la SNOO 2026'));
assert(html.includes('Ionuț'));
assert(html.includes('SNOO-0001'));
assert(html.includes('ROMEXPO'));
assert.strictEqual(reminder.reminderKey('abc'),'snoo-2026-reminder/abc/2026-10-16');
const v=JSON.parse(fs.readFileSync(path.join(root,'vercel.json'),'utf8'));
assert(v.crons&&v.crons.some(x=>x.path==='/api/cron/reminders'));
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
assert(pkg.dependencies&&pkg.dependencies.resend,'resend dependency missing');
const admin=fs.readFileSync(path.join(root,'admin/index.html'),'utf8');
assert(admin.includes('Trimite reminder de test'));
assert(admin.includes('Reminder'));
const data=fs.readFileSync(path.join(root,'api/admin/data.js'),'utf8');
assert(data.includes('reminderSent'));
console.log('reminder system static/pure tests OK');
